USE cm6211_1819_team_5;

ALTER TABLE user_equality
MODIFY COLUMN gender TINYINT(1) DEFAULT NULL,
MODIFY COLUMN religion VARCHAR(40) DEFAULT NULL,
MODIFY COLUMN disability TINYINT(1) DEFAULT NULL,
MODIFY COLUMN post_code_fh VARCHAR(10) DEFAULT NULL,
MODIFY COLUMN age INT(3) DEFAULT NULL;